# Generated by Django 3.2.9 on 2021-11-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_email', models.EmailField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('uah', 'uah')], max_length=3)),
                ('request_date', models.DateField()),
                ('due_to_date', models.DateField()),
                ('transactionID', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
